# Setup
title:        SDN for Optical Networks
tagline:      MAKE OPTICAL NETWORKS AGILE AND INTELLIGENT
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       TOAN
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
