# Setup
title:        SDN for Optical Networks
tagline:      MAKE OPTICAL NETWORKS AGILE AND INTELLIGENT
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       TOAN
  url:        http://osn.webhost.uits.arizona.edu 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman