# Setup
title:        SDN for Optical Networks
tagline:      MAKE OPTICAL NETWORKS AGILE AND INTELLIGENT
baseurl:      "https://github.com/UA-Agile-Cloud/SDN-for-Optical-Networks/tree/master/docs"
paginate:     1
url:          https://ua-agile-cloud.github.io/SDN-for-Optical-Networks/
root:         /SDN-for-Optical-Networks/

# About/contact
author:
  name:       TOAN
  url:        http://osn.webhost.uits.arizona.edu 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
